// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/federation.proto

package federation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUuid    string                 `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Tick          int64                  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	PeerCount     int32                  `protobuf:"varint,3,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	GenesisHash   string                 `protobuf:"bytes,4,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *Heartbeat) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Heartbeat) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *Heartbeat) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

type FleetMove struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FleetId             string                 `protobuf:"bytes,1,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	OwnerUuid           string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	CompressedFleetData []byte                 `protobuf:"bytes,3,opt,name=compressed_fleet_data,json=compressedFleetData,proto3" json:"compressed_fleet_data,omitempty"` // LZ4 blob
	ArrivalTick         int64                  `protobuf:"varint,4,opt,name=arrival_tick,json=arrivalTick,proto3" json:"arrival_tick,omitempty"`
	Signature           []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FleetMove) Reset() {
	*x = FleetMove{}
	mi := &file_proto_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMove) ProtoMessage() {}

func (x *FleetMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMove.ProtoReflect.Descriptor instead.
func (*FleetMove) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{1}
}

func (x *FleetMove) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *FleetMove) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *FleetMove) GetCompressedFleetData() []byte {
	if x != nil {
		return x.CompressedFleetData
	}
	return nil
}

func (x *FleetMove) GetArrivalTick() int64 {
	if x != nil {
		return x.ArrivalTick
	}
	return 0
}

func (x *FleetMove) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MarketOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsBuy         bool                   `protobuf:"varint,5,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`
	SellerUuid    string                 `protobuf:"bytes,6,opt,name=seller_uuid,json=sellerUuid,proto3" json:"seller_uuid,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketOrder) Reset() {
	*x = MarketOrder{}
	mi := &file_proto_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketOrder) ProtoMessage() {}

func (x *MarketOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketOrder.ProtoReflect.Descriptor instead.
func (*MarketOrder) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{2}
}

func (x *MarketOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarketOrder) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *MarketOrder) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketOrder) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MarketOrder) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *MarketOrder) GetSellerUuid() string {
	if x != nil {
		return x.SellerUuid
	}
	return ""
}

func (x *MarketOrder) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_federation_proto protoreflect.FileDescriptor

const file_proto_federation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/federation.proto\x12\n" +
	"federation\"\x82\x01\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x03R\x04tick\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x03 \x01(\x05R\tpeerCount\x12!\n" +
	"\fgenesis_hash\x18\x04 \x01(\tR\vgenesisHash\"\xba\x01\n" +
	"\tFleetMove\x12\x19\n" +
	"\bfleet_id\x18\x01 \x01(\tR\afleetId\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x122\n" +
	"\x15compressed_fleet_data\x18\x03 \x01(\fR\x13compressedFleetData\x12!\n" +
	"\farrival_tick\x18\x04 \x01(\x03R\varrivalTick\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xc4\x01\n" +
	"\vMarketOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x15\n" +
	"\x06is_buy\x18\x05 \x01(\bR\x05isBuy\x12\x1f\n" +
	"\vseller_uuid\x18\x06 \x01(\tR\n" +
	"sellerUuid\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignatureB\x12Z\x10./pkg/federationb\x06proto3"

var (
	file_proto_federation_proto_rawDescOnce sync.Once
	file_proto_federation_proto_rawDescData []byte
)

func file_proto_federation_proto_rawDescGZIP() []byte {
	file_proto_federation_proto_rawDescOnce.Do(func() {
		file_proto_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)))
	})
	return file_proto_federation_proto_rawDescData
}

var file_proto_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_federation_proto_goTypes = []any{
	(*Heartbeat)(nil),   // 0: federation.Heartbeat
	(*FleetMove)(nil),   // 1: federation.FleetMove
	(*MarketOrder)(nil), // 2: federation.MarketOrder
}
var file_proto_federation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_federation_proto_init() }
func file_proto_federation_proto_init() {
	if File_proto_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_federation_proto_goTypes,
		DependencyIndexes: file_proto_federation_proto_depIdxs,
		MessageInfos:      file_proto_federation_proto_msgTypes,
	}.Build()
	File_proto_federation_proto = out.File
	file_proto_federation_proto_goTypes = nil
	file_proto_federation_proto_depIdxs = nil
}
