// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/federation.proto

package federation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The master container for all Federation Traffic
type Packet struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SenderUuid string                 `protobuf:"bytes,1,opt,name=sender_uuid,json=senderUuid,proto3" json:"sender_uuid,omitempty"`
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature  []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 Signature of the 'payload'
	// Types that are valid to be assigned to Content:
	//
	//	*Packet_Heartbeat
	//	*Packet_FleetMove
	Content       isPacket_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSenderUuid() string {
	if x != nil {
		return x.SenderUuid
	}
	return ""
}

func (x *Packet) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Packet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Packet) GetContent() isPacket_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Packet) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Content.(*Packet_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Packet) GetFleetMove() *FleetMove {
	if x != nil {
		if x, ok := x.Content.(*Packet_FleetMove); ok {
			return x.FleetMove
		}
	}
	return nil
}

type isPacket_Content interface {
	isPacket_Content()
}

type Packet_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type Packet_FleetMove struct {
	FleetMove *FleetMove `protobuf:"bytes,5,opt,name=fleet_move,json=fleetMove,proto3,oneof"`
}

func (*Packet_Heartbeat) isPacket_Content() {}

func (*Packet_FleetMove) isPacket_Content() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	GenesisHash   string                 `protobuf:"bytes,3,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"` // Anti-Split-Brain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Heartbeat) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *Heartbeat) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

type FleetMove struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FleetId     string                 `protobuf:"bytes,1,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	OwnerUuid   string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	DestSystem  string                 `protobuf:"bytes,3,opt,name=dest_system,json=destSystem,proto3" json:"dest_system,omitempty"`
	ArrivalTick int64                  `protobuf:"varint,4,opt,name=arrival_tick,json=arrivalTick,proto3" json:"arrival_tick,omitempty"`
	// Compressed Colony/Fleet Data (JSON-over-Protobuf for flexibility)
	CompressedState []byte `protobuf:"bytes,5,opt,name=compressed_state,json=compressedState,proto3" json:"compressed_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FleetMove) Reset() {
	*x = FleetMove{}
	mi := &file_proto_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMove) ProtoMessage() {}

func (x *FleetMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMove.ProtoReflect.Descriptor instead.
func (*FleetMove) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{2}
}

func (x *FleetMove) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *FleetMove) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *FleetMove) GetDestSystem() string {
	if x != nil {
		return x.DestSystem
	}
	return ""
}

func (x *FleetMove) GetArrivalTick() int64 {
	if x != nil {
		return x.ArrivalTick
	}
	return 0
}

func (x *FleetMove) GetCompressedState() []byte {
	if x != nil {
		return x.CompressedState
	}
	return nil
}

var File_proto_federation_proto protoreflect.FileDescriptor

const file_proto_federation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/federation.proto\x12\n" +
	"federation\"\xdf\x01\n" +
	"\x06Packet\x12\x1f\n" +
	"\vsender_uuid\x18\x01 \x01(\tR\n" +
	"senderUuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x125\n" +
	"\theartbeat\x18\x04 \x01(\v2\x15.federation.HeartbeatH\x00R\theartbeat\x126\n" +
	"\n" +
	"fleet_move\x18\x05 \x01(\v2\x15.federation.FleetMoveH\x00R\tfleetMoveB\t\n" +
	"\acontent\"a\n" +
	"\tHeartbeat\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12!\n" +
	"\fgenesis_hash\x18\x03 \x01(\tR\vgenesisHash\"\xb4\x01\n" +
	"\tFleetMove\x12\x19\n" +
	"\bfleet_id\x18\x01 \x01(\tR\afleetId\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12\x1f\n" +
	"\vdest_system\x18\x03 \x01(\tR\n" +
	"destSystem\x12!\n" +
	"\farrival_tick\x18\x04 \x01(\x03R\varrivalTick\x12)\n" +
	"\x10compressed_state\x18\x05 \x01(\fR\x0fcompressedStateB\x12Z\x10./pkg/federationb\x06proto3"

var (
	file_proto_federation_proto_rawDescOnce sync.Once
	file_proto_federation_proto_rawDescData []byte
)

func file_proto_federation_proto_rawDescGZIP() []byte {
	file_proto_federation_proto_rawDescOnce.Do(func() {
		file_proto_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)))
	})
	return file_proto_federation_proto_rawDescData
}

var file_proto_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_federation_proto_goTypes = []any{
	(*Packet)(nil),    // 0: federation.Packet
	(*Heartbeat)(nil), // 1: federation.Heartbeat
	(*FleetMove)(nil), // 2: federation.FleetMove
}
var file_proto_federation_proto_depIdxs = []int32{
	1, // 0: federation.Packet.heartbeat:type_name -> federation.Heartbeat
	2, // 1: federation.Packet.fleet_move:type_name -> federation.FleetMove
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_federation_proto_init() }
func file_proto_federation_proto_init() {
	if File_proto_federation_proto != nil {
		return
	}
	file_proto_federation_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Heartbeat)(nil),
		(*Packet_FleetMove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_federation_proto_goTypes,
		DependencyIndexes: file_proto_federation_proto_depIdxs,
		MessageInfos:      file_proto_federation_proto_msgTypes,
	}.Build()
	File_proto_federation_proto = out.File
	file_proto_federation_proto_goTypes = nil
	file_proto_federation_proto_depIdxs = nil
}
